config/routes.rb
Rails.application.routes.draw do
  resources :animals, only: [:index, :new, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/animal.rb
class Animal < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  def index
    @animals = Animal.all
  end

  def new
    @animal = Animal.new
  end
  
  def create
    if Animal.create!(animal_params)
      redirect_to animals_path
    else
      reder :new
    end
  end

  private

  def animal_params
    params.require(:animal).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/animals/index.html.erb
<ul>
  <% @animals.each do |animal|%>
    <li><%= animal.name %></li>
  <% end %>
</ul>
<%= link_to "Create New Animal Tags!", new_animal_path %>

app/views/animals/new.html.erb
<%= form_with model: @animal do |f| %>
  <%= f.text_field :name %>
  <%= f.submit "Create"%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeployTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>